dbMemo "SQL" ="SELECT Kortit.Kortti, Lataukset.Ajankohta, Lataukset.Lataaja AS Lauseke1, Latauk"
    "set.Korttityyppi, Lataukset.Voimassa, Lataukset.KortinArvo\015\012FROM Kortit IN"
    "NER JOIN Lataukset ON Kortit.[CID] = Lataukset.[Kortti];\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
