dbMemo "SQL" ="SELECT Lataukset.Voimassa, Kortit.Kortti, Lataukset.[Puumerkki], Lataukset.Kortt"
    "ityyppi, Lataukset.KortinArvo, Lataukset.Ajankohta\015\012FROM Kortit INNER JOIN"
    " Lataukset ON Kortit.[CID] = Lataukset.[Kortti]\015\012WHERE (((Kortit.Kortti)=["
    "Forms]![Tervetuloa]![Korttivalinta]));\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
