dbMemo "SQL" ="SELECT Lataukset.Voimassa, Kortit.Kortti, Lataukset.Lataaja, Lataukset.Korttityy"
    "ppi, Lataukset.KortinArvo, Lataukset.Ajankohta\015\012FROM Kortit INNER JOIN Lat"
    "aukset ON Kortit.[CID] = Lataukset.[Kortti]\015\012WHERE (((Kortit.Kortti)=[Loma"
    "kkeet]![Tervetuloa]![Korttivalinta]));\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
