dbMemo "SQL" ="SELECT Count([Lataukset.Kortti]) AS Kaikki, SUM(IIF([Lataukset.Korttityyppi] LIK"
    "E \"*kk\",1,0)) AS Kuukausikortit, SUM(IIF([Lataukset.Korttityyppi] LIKE \"*ap\""
    ",1,0)) AS Aamupvkortit, SUM(IIF([Lataukset.Korttityyppi] LIKE \"*opisk\",1,0)) A"
    "S Opiskelijakortit, SUM(IIF([Lataukset.Korttityyppi] LIKE \"*krt\",1,0)) AS Kert"
    "akortit, (Kaikki - Kuukausikortit - Aamupvkortit - Opiskelijakortit - Kertakorti"
    "t) AS Muut\015\012FROM Lataukset\015\012WHERE ([Lataukset.Voimassa]>=Now());\015"
    "\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
