dbMemo "SQL" ="SELECT DISTINCTROW k.Kortti, m.Maksettu, l.Ladattu, (l.Ladattu - m.Maksettu ) AS"
    " Maksamatta\015\012FROM (Kortit AS k LEFT JOIN (SELECT Kortti, Sum(Summa) AS Mak"
    "settu FROM Maksut GROUP BY Kortti)  AS m ON k.[CID] = m.Kortti) LEFT JOIN (SELEC"
    "T Kortti, SUM(KortinArvo) AS Ladattu FROM Lataukset GROUP BY Kortti)  AS l ON k."
    "[CID] = l.Kortti\015\012WHERE l.Ladattu > m.Maksettu;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
