dbMemo "SQL" ="SELECT k.Kortti AS Card, Ajankohta AS PVM, (-1 * KortinArvo) AS Balance\015\012F"
    "ROM Lataukset\015\012INNER JOIN Kortit AS k ON k.[CID] = Lataukset.Kortti\015\012"
    "\015\012WHERE k.Kortti = Forms!Tervetuloa!Korttivalinta\015\012\015\012UNION SEL"
    "ECT kk.Kortti AS Card, Maksut.PVM, Summa As Balance\015\012FROM Maksut\015\012IN"
    "NER JOIN Kortit As kk ON kk.[CID] = Maksut.Kortti \015\012WHERE kk.Kortti = Form"
    "s!Tervetuloa!Korttivalinta\015\012ORDER BY PVM;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
