dbMemo "SQL" ="SELECT LAST(Voimassa) AS Voimassaolo, LAST(Korttityyppi) AS Kortintyyppi, LAST(K"
    "ortti) AS KorttiID\015\012FROM (SELECT Voimassa, Korttityyppi, Kortti FROM Latau"
    "kset GROUP BY Kortti, Voimassa, Korttityyppi ORDER BY Kortti, Voimassa DESC)  AS"
    " [%$##@_Alias]\015\012GROUP BY Kortti;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbByte "RecordsetType" ="0"
dbBoolean "TotalsRow" ="0"
