dbMemo "SQL" ="SELECT Kortit.Kortti\015\012FROM Kortit INNER JOIN Lataukset ON Kortit.[CID] = L"
    "ataukset.[Kortti]\015\012WHERE (Lataukset.Ajankohta <= [Lomakkeet]![Tervetuloa]!"
    "[RaportitAlku]) AND (Lataukset.Voimassa >= [Lomakkeet]![Tervetuloa]![RaportitLop"
    "pu]);\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
