dbMemo "SQL" ="SELECT Kortit.Kortti, Lataukset.Korttityyppi, Yhteystiedot.Sukunimi, Yhteystiedo"
    "t.Etunimi\015\012FROM Yhteystiedot INNER JOIN (Kortit INNER JOIN Lataukset ON Ko"
    "rtit.[CID] = Lataukset.[Kortti]) ON Yhteystiedot.UID = Kortit.Omistaja\015\012WH"
    "ERE (((Lataukset.Voimassa)>=Forms!Tervetuloa!RaportitAlku) And ((Lataukset.Voima"
    "ssa)<=Forms!Tervetuloa!RaportitLoppu));\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
