dbMemo "SQL" ="SELECT MAX(Lataukset.Voimassa) AS Voimassaolo, Kortit.Kortti, Yhteystiedot.Sukun"
    "imi & \", \" & Yhteystiedot.Etunimi AS Nimi\015\012FROM (Lataukset INNER JOIN Ko"
    "rtit ON Kortit.CID = Lataukset.Kortti) INNER JOIN Yhteystiedot ON Yhteystiedot.U"
    "ID = Kortit.Omistaja\015\012GROUP BY Kortit.Kortti, Yhteystiedot.Sukunimi, Yhtey"
    "stiedot.Etunimi\015\012HAVING MAX(Lataukset.Voimassa)>=Forms!Tervetuloa!Raportit"
    "Alku\015\012AND\015\012MAX(Lataukset.Voimassa)<=Forms!Tervetuloa!RaportitLoppu;\015"
    "\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
