dbMemo "SQL" ="SELECT Yhteystiedot.Etunimi, Yhteystiedot.Sukunimi, Kortit.Kortti, Lataukset.Aja"
    "nkohta, Lataukset.Korttityyppi\015\012FROM (Yhteystiedot INNER JOIN Kortit ON Ko"
    "rtit.Omistaja = Yhteystiedot.[UID]) LEFT JOIN Lataukset ON Kortit.[CID] = Latauk"
    "set.Kortti\015\012WHERE (((Yhteystiedot.Edustusjasen)=True));\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
