dbMemo "SQL" ="SELECT Yhteystiedot.Sukunimi, Yhteystiedot.Etunimi, Yhteystiedot.UID\015\012FROM"
    " Yhteystiedot\015\012WHERE (((Yhteystiedot.UID)=Forms!Tervetuloa!Yhteystietovali"
    "nta)) Or (((Forms!Tervetuloa!Yhteystietovalinta) Is Null));\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
