dbMemo "SQL" ="SELECT DISTINCTROW k.Kortti, (m.Maksettu-l.Ladattu ) AS SaldoaLataamatta\015\012"
    "FROM (Kortit AS k LEFT JOIN (SELECT Kortti, Sum(Summa) AS Maksettu FROM Maksut G"
    "ROUP BY Kortti)  AS m ON k.[CID] = m.Kortti) LEFT JOIN (SELECT Kortti, SUM(Korti"
    "nArvo) AS Ladattu FROM Lataukset GROUP BY Kortti)  AS l ON k.[CID] = l.Kortti\015"
    "\012WHERE m.Maksettu > l.Ladattu;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
