dbMemo "SQL" ="SELECT Maksut.Summa, Maksut.PVM, Maksut.Maksutapa, Yhteystiedot.Sukunimi + \", \""
    " + Yhteystiedot.Etunimi AS Nimi\015\012FROM (Yhteystiedot INNER JOIN Kortit ON Y"
    "hteystiedot.[UID] = Kortit.[Omistaja]) INNER JOIN Maksut ON Kortit.[CID] = Maksu"
    "t.[Kortti]\015\012WHERE (((Maksut.PVM) Between [Forms]![Tervetuloa]![RaportitAlk"
    "u] And [Forms]![Tervetuloa]![RaportitLoppu]));\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
