dbMemo "SQL" ="SELECT Maksut.Summa, Maksut.PVM, Maksut.Maksutapa, Yhteystiedot.Sukunimi, Yhteys"
    "tiedot.Etunimi\015\012FROM (Yhteystiedot INNER JOIN Kortit ON Yhteystiedot.[UID]"
    " = Kortit.[Omistaja]) INNER JOIN Maksut ON Kortit.[CID] = Maksut.[Kortti]\015\012"
    "WHERE (((Maksut.PVM) Between [Forms]![Tervetuloa]![RaportitAlku] And [Forms]![Te"
    "rvetuloa]![RaportitLoppu]))\015\012ORDER BY Yhteystiedot.Sukunimi, Yhteystiedot."
    "Etunimi;\015\012"
dbMemo "Connect" =""
dbBoolean "ReturnsRecords" ="-1"
dbInteger "ODBCTimeout" ="60"
dbByte "RecordsetType" ="0"
dbBoolean "OrderByOn" ="0"
dbByte "Orientation" ="0"
dbByte "DefaultView" ="2"
dbBoolean "FilterOnLoad" ="0"
dbBoolean "OrderByOnLoad" ="-1"
dbBoolean "TotalsRow" ="0"
